drop procedure TryRemovePerson;
drop procedure AddEmployeeToDepartment;
drop procedure RemoveEmployee;
drop procedure AddClient;
drop procedure RemoveClient;
drop procedure AddStandardAccount;
drop procedure AddSavingAccount;
drop procedure RemoveAccount;
drop procedure AddLoan;
drop procedure AddCard;
drop procedure RemoveCard;
drop procedure GetActiveLoansOf;
drop procedure TotalMonthlyPaymentOf;
drop procedure TransferMoney;
drop procedure WithdrawMoney;
drop procedure DepositMoney;
drop procedure MarkCompletedLoans;
drop procedure PayMonthlyLoan;
drop procedure AddYearlyInterest;
drop procedure AddInterestsToSavingAccounts;
drop procedure GetAllIncomingTransactions
drop procedure GetAllOutcomingTransactions;

drop view ClientsWithPersonData;
drop view EmployeesWithPersonData;
drop view AccountsWithOwners;
drop view ActiveLoansWithOwners;
drop view AllTransactions;
